// Centralized goals database for all card difficulties.
const easyCategories = [
  ["Learn how to dig", "Read a book", "Learn how to grow in size", "Learn a new crafting recipe", "Learn how to shrink in size"],
  ["Commit sudoko (kill urself)", "Kill a knight", "Kill a spider", "Kill a zombie", "Kill any flying enemy"],
  ["Collect 100 golden things", "Obtain a card", "Obtain a fruit", "Harvest some plants", "Obtain a key"],
  ["Obtain a map", "Reach any checkpoint", "Save your game", "Save with full health", "Create a backup save"],
  ["Defeat any enemy", "Affect an enemy with a debuff", "Perform a 3-hit combo", "Block an attack", "Dodge an attack perfectly"],
  ["Touch Grass", "Enter a forest", "Enter a jungle", "Enter a castle", "Enter a desert"],
  ["Glitch out of bounds", "Item dupe", "T-pose glitch", "Animation cancel", "Clip through a door"],
  ["Gain an extra life", "Lose a life to fall damage", "Revive an ally", "Find a 1-up mushroom", "Have exactly 0 lives left"],
  ["Look at a woman", "Look at a stone statue", "Look at a metal statue", "Look at the sun (praise optional)", "Observe a sleeping enemy"],
  ["Kill any boss", "Beat any non-tutorial boss", "Defeat a tutorial boss", "Defeat a boss in under 5 minutes", "Defeat a boss using the environment"],
  ["Ride an elevator", "Obtain a hammer", "Obtain a wrench", "Use a lockpick", "Use a grappling hook"],
  ["Increase max health", "Obtain an extra life", "Buy any healing item", "Die", "Increase your defence"],
  ["Obtain a musical instrument", "Play any song", "Listen to the title screen music", "Use any magic", "Find a jukebox"],
  ["Buy an item from a shop", "Buy any type of potion", "Sell an item", "Change the background music", "Buy armor"],
  ["Befriend an enemy", "Stun an enemy", "Interrupt an enemy attack", "Get spotted by a guard", "Taunt an enemy"],
  ["Use an ability connected to fire", "Use an ability connected to ice", "Use an ability connected to lightning", "Double jump", "Dash"],
  ["Meet a merchant", "Rescue any npc", "Meet a ghost", "Meet a king", "Meet a beggar"],
  ["Reveal a secret passage", "Pass through a fake wall", "Fall through a fake floor", "Find a hidden chest", "Discover a secret room"],
  ["Ride any animal", "Obtain a new vehicle", "Ride a boat or raft", "Ride a train", "Drive a car"],
  ["Change your hat", "Equip a matching armor set", "Dye your clothes", "Wear a disguise", "Unequip all clothes"],
  ["Defeat an enemy with melee only", "Obtain a hammer type weapon", "Kill an enemy with a sword", "Use explosives", "Kill a skeleton"],
  ["Beat a boss with only ranged attacks", "Increase your max ammo", "Pick up some ammunition", "Reload any weapon", "Pick up any gun"],
  ["Complete a tutorial", "Level up to level 5", "Reach level 10", "Complete a side quest", "Complete the first level"],
  ["Trigger a tripwire", "Disarm a trap", "Trigger a trap on purpose", "Read the credits", "Survive a trap"],
  ["Change your game language to a different alphabet", "Pause the game during a cutscene", "Make a new character", "Take a screenshot", "Spam the crouch button"]
];

const normalCategories = [
  ["Learn an ability involving water", "Learn an ability involving fire", "Learn an ability involving electricity", "Learn a password", "Learn to fly"],
  ["Kill a mummy", "Kill an enemy while submerged", "Kill a floating hand", "Kill a floating skull", "Kill a ghost"],
  ["Obtain a vegetable", "Obtain explosives", "Obtain a rare artifact", "Obtain a legendary sword", "Obtain a piece of a map"],
  ["Save while poisoned", "Save with 1 HP", "Overwrite a save file", "Save after a boss fight", "Beat a level without saving"],
  ["Defeat an enemy using only kicks", "Defeat an enemy using only punches", "Stack 3 debuffs on one enemy", "Counter an attack", "Survive a 5-enemy ambush"],
  ["Touch a cloud", "Enter a volcano", "Enter outer space", "Climb a mountain", "Reach the top of a hill"],
  ["Become invisible", "Break the physics engine", "Out of bounds skip", "Duplicate an important item", "Find a dev texture"],
  ["Find a hidden life", "Sacrifice a life for an item", "Get revived", "Gain 5 lives in one level", "Finish a stage with 1 life left"],
  ["Observe a rare creature", "Watch an NPC routine", "Read an ancient tablet", "Inspect a painting", "Stare into the abyss"],
  ["Kill a boss with throwing weapons", "Kill an insect boss", "Kill a mechanical boss", "Kill a boss with at least 2 phases", "Defeat a boss without taking damage"],
  ["Turn on a light", "Use a flashlight", "Use a compass", "Use binoculars", "Use a tracker"],
  ["Obtain 3 extra lives", "Drink a healing potion", "Heal an NPC", "Increase your status resistance", "Heal using food only"],
  ["Play a minigame with music", "Unlock a new soundtrack", "Play an instrument perfectly", "Listen to an enemy's song", "Stop the music"],
  ["Buy 3 different items from a shop", "Obtain 100 of any currency", "Sell some loot", "Buy the most expensive item", "Barter with a merchant"],
  ["Get grabbed by an enemy", "Ground a flying enemy", "Capture a thief/criminal", "Encounter an evil version of yourself", "Lure an enemy into a trap"],
  ["Use a healing ability", "Use a time-slowing ability", "Use a mind control ability", "Use a teleport ability", "Use telekinesis"],
  ["Meet a king", "Meet a scientist", "Meet a betrayer", "Meet an alien", "Meet a god"],
  ["Reveal a secret passage", "Turn into an animal", "Discover an easter egg", "Find a hidden developer room", "Find a secret ending"],
  ["Ride a snowboard or a sled", "Complete a minecart section", "Ride a dragon", "Steal a vehicle", "Pilot an aircraft"],
  ["Upgrade your armour", "Upgrade your shoes", "Wear a disguise", "Wear a formal suit", "Change your hair"],
  ["Upgrade a sword", "Uprade a shotgun", "Defeat an armored enemy with melee", "Break an enemy's shield", "Kill a vampire"],
  ["Upgrade a bow", "Complete an autoscroll section", "Shoot a target from far away", "Get a headshot", "Ricochet a bullet"],
  ["Change the water level", "Reach level 25", "Complete a bonus stage", "Complete a stealth section", "Max out a skill"],
  ["Get hit by a boulder", "Push an enemy into a trap", "Dodge a swinging blade", "Survive a poison trap", "Disarm 5 traps"],
  ["Reach 100k points in anything", "Complete a level without killing any enemies", "Play without HUD for 10 minutes", "Finish a level perfectly", "Beat a time trial"]
];

const hardCategories = [
  ["Learn to teleport", "Manipulate time", "Manipulate gravity", "Learn all spells", "Learn to speak to animals"],
  ["Kill a dragon", "Kill a king", "Kill a shapeshifter", "Kill a god/deity", "Kill an invisible enemy"],
  ["Harvest wheat", "Obtain an endgame weapon", "Obtain all collectibles", "Obtain the true ending item", "Obtain every single item"],
  ["Save the game in a hostile area", "Complete the game without saving", "Save only 3 times in a run", "Corrupt a save file", "Delete your save file"],
  ["Escape from prison", "Survive a 1v10 fight", "Defeat enemies using only the environment", "Win a fight blindfolded", "Defeat the hardest enemy type"],
  ["Skip an autoscroller", "Fall from the sky", "Reach the bottom of the ocean", "Enter a parallel dimension", "Travel to the future/past"],
  ["Softlock the game", "Wrong warp", "Trigger an integer overflow", "Sequence break a major item", "Exploit a boss AI"],
  ["Complete a level without dying", "Obtain 5 extra lives", "Beat the game with 1 life", "Gain 99 lives", "Complete a deathless run"],
  ["Observe a celestial event", "Decipher a fictional language", "Watch all credits without skipping", "Observe a hidden cutscene", "Find all lore notes"],
  ["Kill 2 bosses without dying", "Kill a boss without getting hit", "Kill a boss without attacking", "Kill a boss with at least 3 phases", "Defeat a boss with the starting weapon"],
  ["Lower your max health", "Build a complex machine", "Create a custom weapon", "Use a grappling hook to kill", "Use every tool in the game"],
  ["Obtain 1000 of any currency", "Beat a boss with 1 HP left", "Never upgrade health", "Complete a pacifist run", "Beat the game without healing"],
  ["Kill 5 enemies with one explosive", "Unlock the sound test menu", "Find a hidden radio station", "Compose a song", "Sync your actions to the music"],
  ["Play the game with no sound", "Become a millionaire", "Rob a shopkeeper", "Sell your best weapon", "Ruin a merchant's business"],
  ["Buy out a shop's inventory", "Kill 3 enemies in one shot", "Pacify a hostile group", "Turn enemies against each other", "Survive an infinite enemy wave"],
  ["Defeat a giant enemy", "Rescue the princess!", "Use a forbidden magic", "Stop time", "Master every ability"],
  ["Find a mermaid", "Meet the creator/developer", "Meet your clone", "Meet a character from another game", "Meet the final boss early"],
  ["Access a secret world", "Find a glitched area", "Solve a secret puzzle", "Find the dev room", "Find a sequence break secret"],
  ["Complete a vehicle race", "Destroy a vehicle", "Fly a spaceship", "Complete an escort mission", "Ride a mythical creature"],
  ["Obtain the rarest outfit", "Craft a legendary armor", "Complete a no-armor run", "Equip cursed gear", "Wear the most ridiculous outfit"],
  ["Defeat a boss using only melee", "Defeat an enemy with a parry", "Defeat an army with a sword", "Defeat 3 bosses", "Melee a flying enemy"],
  ["Hit a moving target from far", "Complete a sniper mission", "Complete a level using only projectiles", "Don't miss a single shot", "Snipe an enemy mid-air"],
  ["Complete a world", "Reach the max level", "Unlock a secret character", "Complete the hardest difficulty", "Complete the final level"],
  ["Survive a trap gauntlet", "Use a trap to kill a boss", "Disarm a trap blindfolded", "Survive a room full of lasers", "Build a trap"],
  ["Finish a game", "100% completion", "Speedrun a level", "Beat a game under 2 hours", "No hit run of a stage"]
];

window.BINGO_DATA = Object.freeze({
  easy: easyCategories,
  normal: normalCategories,
  hard: hardCategories
});
